name: Generate and Commit Blog Posts JSON

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 0' # هر هفته یکبار

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate posts.json
        run: |
          pip install lxml
          python3 generate_posts_json.py

      - name: Commit and push posts.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add blog/posts.json
          git commit -m "Auto-update blog posts list" || echo "No changes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
